# Generated by Django 4.1.1 on 2022-11-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0002_alter_recipe_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
    ]
