# Generated by Django 4.1.1 on 2022-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0009_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time",
            new_name="timecooking",
        ),
    ]
