# Generated by Django 4.1.1 on 2022-11-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0013_cookingrecipes_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the recipe", max_length=100),
                ),
                (
                    "time",
                    models.PositiveIntegerField(
                        default=30, help_text="Time to do this recipe in minutes"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("Easy", "1"), ("Medium", "2"), ("Difficult", "3")],
                        help_text="Difficulty of this recipe",
                        max_length=32,
                    ),
                ),
                ("URL", models.URLField(help_text="URL wikipedia of the recipe")),
                (
                    "origin",
                    models.CharField(help_text="Country of the recipe", max_length=100),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CookingRecipes",
        ),
    ]
