# Generated by Django 4.1.1 on 2022-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0003_remove_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.PositiveIntegerField(help_text="Difficulty of this recipe"),
        ),
    ]
