# Generated by Django 4.1.1 on 2022-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0005_alter_recipe_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[], help_text="Difficulty of this recipe", max_length=1
            ),
        ),
    ]
