# Generated by Django 4.1.1 on 2022-11-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyApp", "0008_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "1"), ("Medium", "2"), ("Difficult", "3")],
                help_text="Difficulty of this recipe",
                max_length=32,
            ),
        ),
    ]
